### ISSUE TITLE
Regression on displaying non-ASCII characters

### ISSUE THREAD

**Issue by bors-ltd** [esphome/wake-word-voice-assistants#36]
Following https://github.com/esphome/wake-word-voice-assistants/pull/34 (I can only guess), my ESP32-S3-Box-3 now displays black rectangles instead of accentuated letters.

Here are some (literal) screenshots:
![IMG_20241122_125713](https://github.com/user-attachments/assets/cf775906-31b6-45b9-bad3-a07dd7570903)
![IMG_20241122_125739](https://github.com/user-attachments/assets/ab9f56be-5f86-49ab-bf08-d8e2eec051e6)

I don't really have a solution, as the firmware won't compile without that commit. Replacing the font altogether I guess.

It's not breaking, the voice assistant is still functional, but a slight regression nonetheless.

**Comment by HLandstrom** [comment]
I have the same issue.
Took a picture too just in case.

The bars are supposed to be å, ä and ö.

![PXL_20241122_173239650~2.jpg](https://github.com/user-attachments/assets/f7dfc209-3ed9-4320-8b7b-44a9d4782812)

**Comment by drogfild** [comment]
After some debugging, I’ve pinpointed the issue to the configuration of font glyph sets in ESPHome. Currently, when using Google Fonts (gfonts) in YAML configuration, users cannot specify glyph sets to tailor the included character range for rendering. This limitation leads to missing characters (e.g., extended Latin characters like ä, ö, å) even when the font itself supports them.

Here’s an example configuration for context:
```
font:
  - file:
      type: gfonts
      family: Figtree
      weight: 300
      italic: true
    id: font_request
    size: 15
    glyphsets:
      - GF_Latin_Core
  - file:
      type: gfonts
      family: Figtree
      weight: 300
    id: font_response
    size: 15
    glyphsets:
      - GF_Latin_Core
```

By adding glyphsets, the user could define a predefined character set (such as GF_Latin_Core or other supported sets) to ensure the correct glyphs are loaded for their use case. This flexibility would improve support for multilingual text rendering, especially for non-ASCII characters.

https://github.com/googlefonts/glyphsets/blob/main/GLYPHSETS.md#gf-latin-core
https://esphome.io/components/font.html#font-renderer-component

Request:
It would be fantastic if someone could implement this feature as a pull request. It would significantly enhance Assistanses ESPHome's text rendering capabilities and enable more robust font handling for various languages.

Looking forward to feedback or collaboration on this! Let me know if more details or testing are required.
