### ISSUE TITLE
defining

### ISSUE THREAD

**Issue by sejnub** [esphome/wake-word-voice-assistants#44]
defining 
```yaml
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0
```

That fixed it for me on the atom echo. Thanks!
