### ISSUE TITLE
M5Stack Atom Echo does not play timer_finished

### ISSUE THREAD

**Issue by leilich** [esphome/wake-word-voice-assistants#48]
Installed a fresh Atom Echo via https://esphome.io/projects/ as Voice Assistant. (Tried also with 2 other Echoes.)
Firmware: 24.11.1 (ESPHome 2024.11.1)
Integrated in HomeAssistant, not yet adopted by ESPhome Add-On.
Similiar behaviour if adopted to ESPhome and changed the versions resulting in Firmware: 2024.12.2.
```
esp32:
  board: m5stack-atom
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0
```
Wake-Word-Detection and Assist works fine.
Setting a timer for 1sec or 2sec ("Timer für eine Sekunde") lets play the echo the timer_finished sound and flash green. The sound is played while assist answers.
Setting a timer for more than 2sec plays no sound but flashes green.
