### ISSUE TITLE
M5Stack Atom Echo compile fails with esphome 2025.4.0 - esp_psram.h: No such file or directory

### ISSUE THREAD

**Issue by darth-hp** [esphome/wake-word-voice-assistants#98]
Hey there,

Compile fails with the latest upgrade:

```
|-- esp-audio-libs @ 1.1.3
Compiling .pioenvs/m5stack-atom-echo-0ac384/src/esphome/components/psram/psram.o
Compiling .pioenvs/m5stack-atom-echo-0ac384/src/esphome/components/safe_mode/safe_mode.o
Compiling .pioenvs/m5stack-atom-echo-0ac384/src/esphome/components/script/script.o
Compiling .pioenvs/m5stack-atom-echo-0ac384/src/esphome/components/select/select.o
src/esphome/components/psram/psram.cpp:5:10: fatal error: esp_psram.h: No such file or directory
```

YAML config:

``` yaml
substitutions:
  name: m5stack-atom-echo-012345
  friendly_name: Atom-01
packages:
  m5stack.atom-echo-wake-word-voice-assistant: github://esphome/wake-word-voice-assistants/m5stack-atom-echo/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: jGo1Nokia1qzp1NfWj1uvHm1aW1OkLionXN11ynx1Yw=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
